export const getProductIcon = (productType: string): string => {
  const icons: Record<string, string> = {
    flyers: '📄',
    business_cards: '💳',
    booklets: '📖',
    posters: '🖼️',
    brochures: '📚',
    stickers: '🏷️',
    envelopes: '✉️',
    labels: '🏷️',
    blanks: '📋',
    calendars: '📅',
    badges: '🎫',
    business_forms: '📝',
    forms: '📋',
    magnetic_cards: '🧲',
    posters_large: '🖼️',
    perforated_cards: '✂️',
    wall_calendars: '📅',
    table_calendars: '📅',
    notebooks: '📓',
    folders: '📁',
    menus: '🍽️',
    invitations: '💌',
    certificates: '🏆',
    banners: '🚩',
    stands: '🖼️',
    t_shirts: '👕',
    bags: '👜',
    pens: '✏️',
    mugs: '☕',
    keychains: '🔑',
    coasters: '🍽️',
    mouse_pads: '🖱️',
    puzzles: '🧩',
    photo_albums: '📸',
    photo_cards: '🖼️',
    photo_wallpaper: '🖼️',
    flags: '🏳️',
    table_tents: '🏷️',
    placemats: '🍽️',
    table_numbers: '🔢',
    seating_cards: '💺',
    wedding_invitations: '💒',
    wedding_place_cards: '💒',
    wedding_labels: '💒',
    wedding_scrolls: '📜',
    wedding_boxes: '📦',
    wedding_disc_labels: '💿',
    wedding_disc_boxes: '💿'
  };
  return icons[productType] || '📄';
};


